### ISSUE TITLE
Request: option to highlight lines when you visit them

### ISSUE THREAD

**Issue by nesro** [Wattenberger/footsteps-vscode#11]
I would love to have  an option so that: Just when you put the cursor on a line, it will get highlighted in the same way as this extension makes it when you edit a line.

This will be useful for example when you're searching through your code. First, you will find a line with search. Then, you will put cursor under some function and then you will jump to that function definition. All those steps would be highlighted and we could easily go back and forth with the shortcuts for footsteps.

**Comment by Wattenberger** [comment]
I added a setting for adding clicked-on lines to history - hopefully that covers your use case!

**Comment by nesro** [comment]
Wow, thanks for working on this plugin. I will give it another try.
