### ISSUE TITLE
Request: disable for notebooks (or, more long-term, work with new notebook UI)

### ISSUE THREAD

**Issue by sjmielke** [Wattenberger/footsteps-vscode#14]
Right now the extension understandably has a hard time with notebook cells: it highlights the lines within each cells with highlights being shared per cell. Furthermore, attempting to go back and forth with ctrl+alt+arrows puts you into the raw JSON view of the notebook. (To be clear: this is on the VSCode Insiders new native notebook UI, not the old one.)
Since I guess that's not trivial to fix per se, a way to turn it off for notebooks (like #8 requests for diffs) would be useful! Thanks!

**Comment by Akashdesarda** [comment]
Agreed. In fact, if a setting for ignoring specified files is added will be awesome.

**Comment by Wattenberger** [comment]
great idea, sorry about the delay! I added the ability for this to be language-specific, although I'm not sure if there's a good way either add notebook-specific settings or detect when a user is in a notebook. I'm all ears if anyone knows a way!
