### ISSUE TITLE
I would like to install it manually

### ISSUE THREAD

**Issue by arperyan** [Wattenberger/footsteps-vscode#16]
Hi,

I love the extension, and use it on my personal laptop all the time. I would like to use it on my work laptop, but I will need to install it manually as they don't allow extensions. Any clarity on how I can do this, would be greatly appreciated?

Ryan Arpe

**Comment by Faulknerd** [comment]
Hi Ryan,

Give these steps a try. They are based on the info in the webpages below.

1. Download & install node.js
2. Open the "footsteps-vscode" folder in a terminal. Install the following dependencies:
```
    npm install -g yarn
    npm install webpack webpack-cli
```
3. Also install Microsoft's extension tool:
`    npm install -g vsce`
4.  Bundle the extension into a VSIX file:
`    vsce package`
5. You will now have a VSIX file in the folder. You can deploy this to any machine. 
6. The first webpage will tell you how to install the extension in VS Code. Search for "VSIX"

[https://code.visualstudio.com/docs/editor/extension-marketplace](https://code.visualstudio.com/docs/editor/extension-marketplace) (Installing an extension from a VSIX file)
[https://code.visualstudio.com/api/working-with-extensions/publishing-extension](https://code.visualstudio.com/api/working-with-extensions/publishing-extension) (Creating a VSIX file)

**Comment by arperyan** [comment]
Thanks
