### ISSUE TITLE
Incompatibility with Bracket Pair Colorizer 2

### ISSUE THREAD

**Issue by FALLAI-Denis** [Wattenberger/footsteps-vscode#18]
When installing [Footsteps](https://marketplace.visualstudio.com/items?itemName=Wattenberger.footsteps) and [Bracket Pair Colorizer 2](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2) together, highlighting pairs of brackets by Bracket Pair Colorizer 2 no longer works.

The B[racket Pair Colorizer 2 project](https://github.com/CoenraadS/Bracket-Pair-Colorizer-2) was recently archived by its developer, no explanation for that.
Unable to report the problem there.

**Comment by GavG** [comment]
Hi, it seems the Bracket Pair Colorizer 2 package was deprecated as its functionality has now been incorporated into VSCode natively. I had similar issues, uninstalling Bracket Pair Colorizer 2 resolved the issues and bracket pair highlighting now works alongside this package.

**Comment by Wattenberger** [comment]
Sounds like this is resolved, but please shout if not!
