### ISSUE TITLE
Request: support per-language configuration

### ISSUE THREAD

**Issue by CWempe** [Wattenberger/footsteps-vscode#19]
I would like to disable footsteps for certain languages like `markdown` or `plain text`.
But the option `footsteps.doHighlightChanges` does not support this.

![image](https://user-images.githubusercontent.com/1270359/122654204-14b31d80-d14a-11eb-9638-edb89d63356a.png)

**Comment by joshmu** [comment]
Would also love to see this 👍

**Comment by Wattenberger** [comment]
added in https://github.com/Wattenberger/footsteps-vscode/commit/e1799c10d329d9a168896d5ab41a35f1b965c595
sorry about the delay!
