### ISSUE TITLE
New command suggestion: clear all the changes of the current project/window

### ISSUE THREAD

**Issue by AdmiralRazorbeard** [Wattenberger/footsteps-vscode#4]
Or even better: an option to would clear all the highlighted lines of the current project after each commit but it may be too complicated.
A command to clear all the changes would already be great 👍

**Comment by rach7110** [comment]
I also like the idea to clear all highlighted lines. I find the highlights useful when I'm editing code. But distracting when I'm reading code. A toggle of the highlighted lines would be neat!

**Comment by Wattenberger** [comment]
great idea, sorry about the delay!
