### ISSUE TITLE
doHighlightCurrentlyFocusedChunk doesNotHighlightCurrentlyFocusedChunk

### ISSUE THREAD

**Issue by garthk** [Wattenberger/footsteps-vscode#5]
Highlights stubbornly disappear If I click on them or use `footsteps.skipBack` or `footsteps.skipForwards` (⌃⌥← and ⌃⌥→ on macOS) to navigate to them, despite `"footsteps.doHighlightCurrentlyFocusedChunk": true` in my `settings.json`.

I'm running Footsteps 0.1.0 on VS Code 1.53.2.

**Comment by Wattenberger** [comment]
good catch, sorry about the delay!
