### ISSUE TITLE
Request: do not highlight in the Git diff viewer

### ISSUE THREAD

**Issue by sbesselsen** [Wattenberger/footsteps-vscode#8]
Hi, I really like the extension! I use the internal Git features of VS Code to review diffs before committing. It highlights removed and added lines. The highlighting from footsteps is then superimposed on that highlighting, which makes it very hard to understand the diff. I think the default should be not to show footsteps highlighting in diffs, or make it optional to do so.

**Comment by Wattenberger** [comment]
this is frustrating! looks like we can only detect the left-hand side of a diff, but I'll keep an eye on this issue and update if that changes!

https://github.com/microsoft/vscode/issues/97683
